### ISSUE TITLE
Offline maps not loading

### ISSUE THREAD

**Issue by gerkelly** [TizioFittizio/OsmDroidOfflineMap#1]
I downloaded and compiled this project and positioned my map over a location which is covered by a set of map tiles in .png format compressed into a .zip archive in a directory structure in this format: /mapnik/x/y/z.png

I have tried putting the .zip file in /storage/emulated/0/osmdroid and /storage/emulated/0/osmdroid/tiles which is where the cache.db and cache.db-journal files reside (this directory structure existed already).

When I run the app it runs but shows a blank grid instead of a map.

**Comment by TizioFittizio** [comment]
Did you try to enable these flags in the `MainActivity`?

```
 // If you are experiencing issues consider enabling those
 // Configuration.getInstance().setDebugMode(true);
 // Configuration.getInstance().setDebugMapView(true);
 // Configuration.getInstance().setDebugTileProviders(true);
```
Can you post the logcat output with these flags active?

**Comment by gerkelly** [comment]
Thanks for your reply.

The Logcat file is attached.

[logcat.txt](https://github.com/TizioFittizio/OsmDroidOfflineMap/files/4162330/logcat.txt)

**Comment by TizioFittizio** [comment]
Unfortunately, I'm not able to reproduce this, when a grey grid is displayed the map is not loaded correctly

I remember having struggle with this and I opened an issue long ago: https://github.com/osmdroid/osmdroid/issues/577

I suggest you open an issue on the [official osmdroid repository](https://github.com/osmdroid/osmdroid/issues), I'm sorry to not be able to help, good luck

**Comment by gerkelly** [comment]
Hi @TizioFittizio 

Thanks for your reply. I managed to fix this with the help of someone on [Stackoverflow](https://stackoverflow.com/questions/60076218/osmdroid-offline-maps-not-loading) 

I will close this issue now.

Gerald
